name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  frontend:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command in frontend directory
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command in frontend directory
